spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:mysql://localhost:3306/goosage_test
    username: test_user
    password: test_pw

server:
  port: 8085

logging:
  file:
    name: logs/test.log
