package com.goosage.domain.predict;

public enum PredictionReasonCode {
    DATA_POOR,
    LOW_ACTIVITY_3D,
    REVIEW_WRONG_PENDING,
    RECOVERY_PROGRESS,
    RECOVERY_SAFE,
    LOW_QUALITY_OPEN,
    GOOD_PROGRESS,
    HABIT_STABLE,
    MINIMUM_ACTION,
    HABIT_COLLAPSE,
    TODAY_DONE,
    WRONG_HEAVY,
    STABLE_PROGRESS
}